function init(self)
	-- all of the "self" declared trackers go here
	self.story = require "./lua/story"
	self.current_chapter = "intro" -- this will be dynamic from the last saved chapter
end

function on_message(self, message_id, message, sender)
	-- here we would receive messages based on map selection or other things that may switch story or dialog
end

local function switch_chapter(self, chapter_name)
	-- possibly save state of the previous chapter?
	self.current_chapter = chapter_name
end