local druid = require("druid.druid")
local save_manager = require "scripts.lua.save_manager"
local story_manager = require "scripts.lua.story_manager"
local typewriter = require "scripts.widgets.typewriter"

local TOUCH = hash("touch")

-- TODO: bug - when the player responds the new_height gets all messed up...
-- updates the container size based on the text (for scroll)
local function get_text_size(self, node)
	local font_name = gui.get_font(node) -- TODO: this only gets the size of the current node (not all combined)
	local font = gui.get_font_resource(font_name)
	local text = gui.get_text(node)
	local metrics = resource.get_text_metrics(font, text)
	
	return metrics.height
	--local new_height = metrics.height

	--if new_height >= content_box_size.y then
		-- only increase scroll_text_content box new text exceeds current content height
		--gui.set_size(self.text_content_node, vmath.vector3(content_box_size.x, new_height, 0))
	--end
end

local function write_text(self, text_table)
	if self.current_widget_text then
		self.current_widget_text = ""
	end

	if self.current_widget then
		self.current_widget = nil
	end
	
	local _, text = next(text_table)
	local current_content_size = gui.get_size(self.text_content_node)

	local nodes = gui.clone_tree(gui.get_node("text_template"))
	local new_text_node = nodes["text_template"]
	-- temporarily set text to measure height
	gui.set_text(new_text_node, text)
	local new_text_size = get_text_size(self, new_text_node)
	-- remove text after measurements so we can use the typewriter
	gui.set_text(new_text_node, "")

	local buffer = 20
	local new_content_height = current_content_size.y + new_text_size + buffer
	gui.set_enabled(new_text_node, true)

	if new_content_height >= current_content_size.y then
		gui.set_size(new_text_node, vmath.vector3(current_content_size.x, new_content_height, 0)) -- consider scale??
	end

	self.scroll:update_view_size()
	
	-- handle auto-scroll
	timer.delay(0, false, function()
		self.scroll:scroll_to_percent(vmath.vector3(0, 0, 0), true)
	end)

	-- typewriter
	self.current_widget = {
		text_node = new_text_node,
		timer_handle = nil
	}
	self.current_widget = typewriter.new(new_text_node, 0.05)
	self.current_widget:type_text(text)
	self.current_widget_text = text
end

local function destroy_player_options(self)
	for _, item in pairs(self.player_option_buttons) do
		self.druid:remove(item.button)
		gui.delete_node(item.box)
	end

	self.player_option_buttons = {}
end

local function create_player_option(self, option_key, option_text, index)
	local nodes = gui.clone_tree(gui.get_node("player_selection_template"))
	local box = nodes["player_selection_template"]
	local text_nodes = nodes["player_selection_text_template"]

	-- re-parent the cloned box to the container
	gui.set_parent(box, gui.get_node("player_response_container"))
	
	local size = gui.get_size(box)
	local y_offset = size.y * (index - 1) -- maybe add spacing??

	gui.set_position(box, vmath.vector3(0, -y_offset, 0))
	gui.set_enabled(box, true)
	gui.set_text(text_nodes, option_text)

	local button = self.druid:new_button(box, function()
		-- gui.set_text(self.story_text_node, story_manager:select_player_option(option_key)) -- "a", "b", ..."z"
		-- TODO: this is adding too much space - could be something with the \n??
		-- TODO: also we might be able to handle this in a way we don't have to call update_text_size, and scroll stuff in multiple places
		write_text(self, story_manager:select_player_option(option_key))
		destroy_player_options(self)
	end)

	table.insert(self.player_option_buttons, {
		button = button,
		box = box
	})
end

--==============--
--== BUILTINS ==--
--==============--
function init(self)
	msg.post(".", "acquire_input_focus")
	self.druid = druid.new(self)

	-- init save data
	story_manager:set_chapter(save_manager.save_data.story_chapter)
	story_manager:set_sequence(save_manager.save_data.sequence_key)
	
	-- declare story scope
	self.scroll = self.druid:new_scroll("story_text_container", "story_text_content")
	self.scroll:set_horizontal_scroll(false)
	self.scroll:set_inert(true)

	-- declare nodes
	self.text_widgets = {} -- set to table because we use gui.clone_tree()
	self.text_content_node = gui.get_node("story_text_content")
	self.next = gui.get_node("next")
	self.player_option_buttons = {}

	-- start writing the new text
	write_text(self, story_manager:fetch_next_sequence())

	-- decide what we want to do when the story get's paused (for now, just fetch player options)
	story_manager.on_state_changed = function(new_state)
		if new_state == "paused" then
			-- create buttons based on the number of options
			local player_options = story_manager:fetch_player_options()
			local idx = 1

			-- TODO: currently the options come in randomly (lua nature), either sort keys (alphabetically) or find another solution
			for k, v in pairs(player_options) do
				create_player_option(self, k, v, idx)
				idx = idx + 1
			end
		end
	end
end

function on_message(self, message_id, message, sender)
	-- messages
end

function update(self, dt)
	-- TODO: implement typewriter.lua
	self.druid:update(dt)
end

function on_input(self, action_id, action)
	local is_input_consumed = self.druid:on_input(action_id, action)
	
	if not is_input_consumed and action_id == TOUCH and action.pressed then
		if story_manager.state ~= "paused" and gui.pick_node(self.next, action.x, action.y) then
			if self.current_widget.timer_handle then
				self.current_widget:skip(self.current_widget_text)
			else
				write_text(self, story_manager:fetch_next_sequence())
			end
		end
	end

	return is_input_consumed
end

function final(self)
	self.druid:final()
	-- Save state of the story
end